services:
  ok-api:
    image: ok-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - res:/app/bin_results
      
volumes:
  res:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./bin_results
